# Generated by Django 4.2.5 on 2023-09-21 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None, verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
