# Generated by Django 4.2.5 on 2023-09-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options_and_more'),
        ('empleados', '0004_alter_empleado_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='empleados.habilidades', verbose_name='Habilidades'),
        ),
    ]
